/* DO NOT CHANGE THIS FILE! GENERATED BY @SELF@ */

#include "str_to_int.h"

#include <stdlib.h>
#include "checked_arithmetic.h"

/* TODO: ignore leading zeros,
 * except leading 0b, 0o and 0x.

 * Allow to pass in a target base.

 * Allow to have leading + or -
 * (no spaces between them and number allowed).

 * Allow single underscores in the number
 * (except the first, last and characteres right after 0b,0o,0x).
 * Not allowed: _234, 456_, 0x_F, 0xF_
 * Allowed: 2_3_4, 0xF_A
 */

/* SEE:
 * https://github.com/lattera/glibc/blob/895ef79e04a953cac1493863bcae29ad85657ee1/stdlib/strtol_l.c
 * https://github.com/python/cpython/blob/6557af669899f18f8d123f8e1b6c3380d502c519/Objects/longobject.c#L2518
 */

@S2U@

@S2S@
